import { StyleSheet, Platform } from "react-native";
import colorPallette from "./colorPallette";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colorPallette.ghostWhite,
    alignItems: "center",
  },
  sav: {
    height: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  headerText: {
    fontSize: 50,
    fontWeight: "bold",
    marginVertical: 20,
    textAlign: "center",
  },
  horizontalArrangement: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  optionButtonsContainer: {
    width: "100%",
    alignItems: "center",
  },
  optionButton: {
    marginHorizontal: 20,
    width: "80%",
    backgroundColor: colorPallette.tuftsBlue,
    padding: 20,
    borderRadius: 200,
    alignItems: "center",
    shadowColor: colorPallette.tuftsBlue,
    shadowRadius: 10,
    shadowOpacity: 0.5,
    shadowOffset: { width: 0, height: 0 },
    marginTop: 20,
  },
  optionButtonText: {
    fontSize: 25,
    color: colorPallette.ghostWhite,
    fontWeight: "bold",
  },
  subOptionButton: {
    marginHorizontal: 20,
    width: "80%",
    padding: 20,
    alignItems: "center",
    marginTop: 20,
  },
  subOptionButtonText: {
    fontSize: 25,
    color: colorPallette.mediumSlateBlue,
    fontWeight: "bold",
    fontStyle: "italic",
  },
  optionTextInput: {
    marginHorizontal: 20,
    width: "80%",
    backgroundColor: colorPallette.ghostWhite,
    borderColor: colorPallette.tuftsBlue,
    borderWidth: 4,
    padding: 20,
    borderRadius: 200,
    alignItems: "center",

    marginTop: 20,
    fontSize: 20,
    color: colorPallette.tuftsBlue,
    fontWeight: "bold",
  },
  errorText: {
    marginTop: 20,
    fontSize: 20,
    fontWeight: "bold",
    fontStyle: "italic",
    color: colorPallette.redPigment,
    width: "100%",
    textAlign: "center",
  },
  eventItem: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    borderRadius: 20,
    padding: 20,
    backgroundColor: colorPallette.tuftsBlue,
    alignSelf: "center",
    marginVertical: 10,
  },
  eventItemLeftContent: {
    flex: 1,
    alignItems: "flex-start",
  },
  eventItemRightContent: {
    flex: 1,
    alignItems: "flex-end",
    paddingTop: 5,
  },
  eventItemTitle: {
    fontSize: 20,
    fontWeight: "bold",
    fontStyle: "italic",
    marginBottom: 10,
  },
  eventItemInfo: {
    fontSize: 17,
    fontWeight: "bold",
    marginBottom: 5,
  },
  eventItemEditButtonContainer: {
    flex: 1,
  },
  eventItemEditButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 20,
    backgroundColor: "#ffffff44",
    borderRadius: 20,
    padding: 20,
    marginBottom: 5,
  },
  messageButton: {
    flex: 0.1,
    alignItems: "center",
    justifyContent: "center",
    margin: 20,
    backgroundColor: colorPallette.blackCoffee,
    borderRadius: 20,
    padding: 20,
    marginBottom: 5,
  },
  eventItemEditButtonText: {
    fontSize: 16,
    fontWeight: "bold",
  },
  subText: {
    textAlign: "center",
    fontSize: 20,
    fontStyle: "italic",
    marginHorizontal: 20,
    marginBottom: 20,
  },
  alertItem: {
    backgroundColor: colorPallette.tuftsBlue,
    padding: 15,
    paddingVertical: 8,
    borderRadius: 10,
    width: "95%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  alertText: {
    fontSize: 18,
    fontWeight: "bold",
    fontStyle: "italic",
    color: colorPallette.ghostWhite,
    flex: 0.8,
    textAlignVertical: "center",
    marginRight: 20,
  },
  alertButton: {
    flex: 0.2,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: "#ffffff44",
  },
  alertButtonText: {
    fontSize: 15,
    fontWeight: "bold",
    color: colorPallette.ghostWhite,
    textAlign: "center",
  },
  personItem: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    borderRadius: 20,
    padding: 20,
    backgroundColor: "#ffffff44",
    alignSelf: "center",
    marginVertical: 10,
  },
  personItemText: {},
});

export default styles;
